services:
  - type: web
    name: instadm
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn instadm.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: instadm.settings
      - key: PYTHON_VERSION
        value: 3.11
